name: Build and Deploy

on:
  push:
    branches:
      - main  # main branch'ga push qilishda ishga tushadi

jobs:
  build:
    runs-on: ubuntu-latest  # Eng so‘nggi Ubuntu runner'ini ishlatish

    steps:
    # Kodni checkout qilish
    - name: Checkout repository
      uses: actions/checkout@v2

    # Android uchun JDK ni o‘rnatish
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Android APK ni qurish
    - name: Build APK
      run: |
        cd android
        ./gradlew build --stacktrace

    # iOS qurish uchun Xcode o‘rnatish
    - name: Set up Xcode
      uses: apple-actions/setup-xcode@v2
      with:
        xcode-version: '12.5'  # Xcode versiyasini belgilash (loyihangizga mos ravishda o‘zgartirishingiz mumkin)

    # iOS qurish
    - name: Build iOS
      run: |
        cd ios
        xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphoneos -configuration AppStoreDistribution clean archive -archivePath $PWD/build/YourApp.xcarchive

    # Android APK ni saqlash
    - name: Upload APK to storage
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: android/app/build/outputs/flutter-apk/app-release.apk

    # iOS arxivini saqlash
    - name: Upload iOS archive to storage
      uses: actions/upload-artifact@v2
      with:
        name: ios-archive
        path: ios/build/YourApp.xcarchive
