name: Build and Deploy

on:
  push:
    branches:
      - main  # Asosiy branchga push qilinganida

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu operatsion tizimida ishlash

    steps:
    # Repozitoriyadan kodni olish
    - name: Checkout repository
      uses: actions/checkout@v2

    # Android APK yaratish
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build APK
      run: |
        cd android
        ./gradlew build --stacktrace

    # iOS yaratish
    - name: Set up Xcode
      uses: apple-actions/setup-xcode@v3
      with:
        xcode-version: '12.5'

    - name: Build iOS
      run: |
        cd ios
        xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphoneos -configuration AppStoreDistribution clean archive -archivePath $PWD/build/YourApp.xcarchive

    # APK faylini yuklash
    - name: Upload APK to storage
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: android/app/build/outputs/flutter-apk/app-release.apk

    # iOS arxivini yuklash
    - name: Upload iOS archive to storage
      uses: actions/upload-artifact@v3
      with:
        name: ios-archive
        path: ios/build/YourApp.xcarchive
